name: Unit Testing

on: pull_request

jobs:
  run-jest-tests:
    name: Client Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: client/yarn.lock
          node-version: '20.x'
          cache: 'yarn'
          
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile

      - name: Run Jest Tests
        working-directory: ./client
        run: yarn test
        
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.4.0
            
