name: Jest Automatic Testing

on: pull_request

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install

      - name: Run Jest Tests
        run: yarn test
